// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package storage

import (
	"time"

	"github.com/gofrs/uuid"
	"musicd/internal/player/domain"
)

type Player struct {
	ID           uuid.UUID
	HostID       uuid.UUID
	CurrentTrack domain.NullCurrentTrack
	Queue        domain.Queue
	UpdatedAt    time.Time
	CreatedAt    time.Time
}
