// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package storage

import (
	"time"

	"github.com/gofrs/uuid"
	null "gopkg.in/guregu/null.v4"
	"musicd/internal/track/domain"
)

type Track struct {
	ID         uuid.UUID
	ArtistID   uuid.NullUUID
	AlbumID    uuid.NullUUID
	Title      string
	Duration   null.Int
	Files      domain.Files
	UploadedBy uuid.UUID
	UploadedAt time.Time
}
