package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"musicd/graph/model"
)

// Tracks is the resolver for the tracks field.
func (r *queryResolver) Tracks(ctx context.Context, first int, after *string, before *string) (*model.TrackList, error) {
	return r.trackResolver.Tracks(ctx, first, after, before)
}
